baseURL = 'https://ScotuzziJr.github.io/marc.py/'
languageCode = 'pt-br'
title = 'marc.py'
theme='terminal'

[params]
 author = "marc"
 description = "Software é político"
 
 contentTypeName = "posts"

 themeColor = "green"

 centerTheme = true
 autoCover = true

[languages]
   [languages.en]
   title = "marc.py"
   subtitle = "Software é político"

   [languages.en.params.logo]
      logoText = "marc.py"

